import type { GamePhase, GameSnippet } from '../../types';

export type AudioPhraseGameViewProps = {
  showHeader: boolean;
  roundIndex: number;
  totalRounds: number;
  lives: number;
  phase: GamePhase;
  loading: boolean;
  isFinished: boolean;
  outOfLives: boolean;
  currentSnippet: GameSnippet | null;
  currentItem: GameSnippet | null;
  currentWords: string[];
  translationOptions: string[];
  showTranslationQuestion: boolean;
  showMissingQuestion: boolean;
  showOddWordQuestion: boolean;
  missingIndices: number[];
  missingSlots: (string | null)[];
  missingOptions: string[];
  missingShake: boolean;
  oddWordOptions: string[];
  oddWordAnswer: string | null;
  selectedOddWord: string | null;
  selectedTranslation: string | null;
  oddWordShake: boolean;
  slots: (string | null)[];
  availableWords: string[];
  message: string | null;
  isCorrect: boolean | null;
  showCheck: boolean;
  questionMessage: string | null;
  questionCorrect: boolean | null;
  isAnswerWrong: boolean;
  showSkip: boolean;
  onTranslationAnswer: (value: string) => void;
  onMissingPick: (value: string) => void;
  onMissingRemove: (slotIndex: number) => void;
  onOddWordPick: (value: string) => void;
  onAdvancePhase: () => void;
  onWordDrop: (word: string, slotIndex: number) => void;
  onReturnWord: (word: string) => void;
  onWordClick: (word: string) => void;
  onSlotClick: (slotIndex: number) => void;
};
