export const AUDIO_PHRASE_GAME_TEXT = {
  title: 'Мини-игра: Слушай и собери фразу',
  round: 'Раунд',
  translationTitle: 'Выбери перевод',
  loading: 'Загружаем фразы...',
  empty: 'Нет подходящих сниппетов в пуле.',
  finished: 'Серия завершена! Отличная работа.',
  correct: 'Верно!',
  retry: 'Попробуй еще раз',
  skip: 'Пропустить',
  next: 'Далее',
  slotHint: 'Нажмите, чтобы вернуть',
  missingTitle: 'Вставь пропущенные слова',
  oddWordTitle: 'Какого слова тут нет?',
  assembleTitle: 'Собери фразу',
  defaultTitle: 'Что тут говорится?',
  gameOver: 'Игра окончена. Жизни закончились.',
  wrongAnswer: 'Неверно. Попробуй еще раз',
};
