export const mockBooks = [
  {
    id: "mock-1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description:
      "A classic novel of the Roaring Twenties, about the mysterious Jay Gatsby and the people drawn into his orbit.",
    coverUrl:
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=640&auto=format&fit=crop",
    fileUrl: "https://example.com/books/gatsby.txt",
    language: "en",
    wordCount: 47000,
    inShelf: true,
    progress: { position: 0, progress: 0.65, updatedAt: new Date().toISOString() },
    level: "B1",
    minutes: 20,
    difficulty: "Средняя",
    category: "Для начинающих",
    readers: 1200,
    rating: 4.8,
  },
  {
    id: "mock-2",
    title: "Sherlock Holmes",
    author: "Arthur Conan Doyle",
    description: "A legendary detective story full of twists and deductions.",
    coverUrl:
      "https://images.unsplash.com/photo-1529158062015-cad636e205a0?q=80&w=640&auto=format&fit=crop",
    fileUrl: "https://example.com/books/sherlock.txt",
    language: "en",
    wordCount: 38500,
    inShelf: true,
    progress: { position: 0, progress: 0.32, updatedAt: new Date().toISOString() },
    level: "B2",
    minutes: 35,
    difficulty: "Средняя",
    category: "Классика",
    readers: 930,
    rating: 4.7,
  },
  {
    id: "mock-3",
    title: "1984",
    author: "George Orwell",
    description: "A chilling dystopian novel about surveillance and control.",
    coverUrl:
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=640&auto=format&fit=crop",
    fileUrl: "https://example.com/books/1984.txt",
    language: "en",
    wordCount: 89000,
    inShelf: false,
    progress: null,
    level: "C1",
    minutes: 55,
    difficulty: "Сложная",
    category: "Классика",
    readers: 1500,
    rating: 4.9,
  },
  {
    id: "mock-4",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupery",
    description: "A poetic tale with deep themes of life and friendship.",
    coverUrl:
      "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?q=80&w=640&auto=format&fit=crop",
    fileUrl: "https://example.com/books/prince.txt",
    language: "en",
    wordCount: 17000,
    inShelf: false,
    progress: null,
    level: "A1",
    minutes: 15,
    difficulty: "Легкая",
    category: "Для начинающих",
    readers: 540,
    rating: 4.6,
  },
  {
    id: "mock-5",
    title: "Short Stories for Kids",
    author: "Classic Tales",
    description: "Easy stories for fast practice and quick wins.",
    coverUrl:
      "https://images.unsplash.com/photo-1455885666463-331e3c1fbc0a?q=80&w=640&auto=format&fit=crop",
    fileUrl: "https://example.com/books/stories.txt",
    language: "en",
    wordCount: 12000,
    inShelf: false,
    progress: null,
    level: "A1",
    minutes: 10,
    difficulty: "Легкая",
    category: "Для начинающих",
    readers: 320,
    rating: 4.4,
  },
  {
    id: "mock-6",
    title: "Pride & Prejudice",
    author: "Jane Austen",
    description: "A beloved classic about love, pride, and prejudice.",
    coverUrl:
      "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?q=80&w=640&auto=format&fit=crop",
    fileUrl: "https://example.com/books/pride.txt",
    language: "en",
    wordCount: 94000,
    inShelf: false,
    progress: null,
    level: "B2",
    minutes: 50,
    difficulty: "Сложная",
    category: "Классика",
    readers: 880,
    rating: 4.7,
  },
];

